targets:
  $default:
    sources:
      - lib/**
      - plugins/rhttp/lib/src/rust/**
      - $package$
      - lib/$lib$

    builders:
      freezed:
        generate_for:
          - lib/**
          - plugins/rhttp/lib/src/rust/**
